FROM python:3.10.12-slim-buster

# 작업 디렉터리를 설정합니다.
WORKDIR /app

# 필요한 시스템 패키지를 설치합니다.
RUN apt-get update && apt-get install -y \
    gcc \
    g++ \
    && rm -rf /var/lib/apt/lists/*

# requirements.txt를 Docker 이미지 안에 복사합니다.
COPY ./requirements.txt /app/requirements.txt

# requirements.txt에 명시된 패키지를 설치합니다.
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# 소스 코드를 복사합니다.
COPY . /app

EXPOSE 1101

# Run app.py when the container launches
CMD ["gunicorn", "-k", "uvicorn.workers.UvicornWorker", "main:app", "--bind", "0.0.0.0:1101", "--workers", "2", "--forwarded-allow-ips", "*"]